### ISSUE TITLE
Crash with "enter.transition is not a function"

### ISSUE THREAD

**Issue by sidecus** [chrisrzhou/react-wordcloud#22]
Seems like related to [this issue](https://github.com/d3/d3-selection/issues/185).

**Comment by chrisrzhou** [comment]
Hi @sidecus, I read through the issue link you provided and applied the `resolutions` in `package.json` fix.  I'm not seeing the issue on my side, so do you mind helping me check on your side by pulling the latest code in `master` branch?  Thanks!

**Comment by sidecus** [comment]
@chrisrzhou - Thank you for the quick response! Unfortunately it didn't solve the issue. I'll try to see whether I can have a standalone repro of this.

**Comment by sidecus** [comment]
I was not able to isolate this. Anyways I now do believe it's an issue with webpack - it doesn't execute the d3 transition prototype extension code no matter whether "import 'd3-transition'" is there or not.
I didn't find a good workaround, unfortunately. Maybe providing the option to bypass transition will at least enable me to use this cool lib.

Thank you for the help though. I think we can close this.

**Comment by davidjb** [comment]
I had the same issue (`TypeError: t.transition is not a function` with a backtrace steeped in Webpack, `./node_modules/d3-selection/src/selection/call.js/__webpack_exports__.default` etc).  It started occurring after upgrading `react-wordcloud` from 1.2.4 to 1.2.5 (with the issue persisting when upgrading to 1.2.6 and then 1.2.7). My issue was definitely Webpack and dependency-related so I ended up removing my `yarn.lock` file and reinstalling my project to resolve the issue.  I don't specifically know what's fixed the issue but I see my `yarn.lock` file now has dual resolutions for `d3-selection@1.4.2, d3-selection@^1.1.0` so I don't need the workaround in the linked issue.

**Comment by chrisrzhou** [comment]
Hey @davidjb thanks for some of the details here.  I'm not very knowledgeable with package build pipelines.  Based on your understanding, do you think the `resolutions` field in https://github.com/chrisrzhou/react-wordcloud/blob/main/package.json#L69-L71 no longer applies and we can remove it?

I haven't seen issues on my end (with either `npm` or `yarn`).  Then again, I usually blow away `node_modules` and `*-lock.json` files when I test/develop to make sure the package works for clean installs.  Is this something that is not related to this project and something more specific with stale lockfiles?

**Comment by davidjb** [comment]
I'm no expert but I've seen Webpack blow up like this when you've got two different versions or instances of the same package in the build.  ~I can't find the reference to it but~ I've experienced this in React itself when developing packages -- each package is looking at a different instance and :boom: ; general details at https://reactjs.org/warnings/invalid-hook-call-warning.html#duplicate-react.

In my case, my previous `yarn.lock` (committed 06:57 UTC on 6 Aug 2020) looked like this, which was causing broken builds:
```
d3-selection@1.4.2:
  version "1.4.2"
  resolved "https://registry.yarnpkg.com/d3-selection/-/d3-selection-1.4.2.tgz#dcaa49522c0dbf32d6c1858afc26b6094555bc5c"
  integrity sha512-SJ0BqYihzOjDnnlfyeHT0e30k0K1+5sR3d5fNueCNeuhZTnGw4M4o8mqJchSwgKMXCNFo+e2VTChiSJ0vYtXkg==

d3-selection@^1.1.0:
  version "1.4.1"
  resolved "https://registry.yarnpkg.com/d3-selection/-/d3-selection-1.4.1.tgz#98eedbbe085fbda5bafa2f9e3f3a2f4d7d622a98"
  integrity sha512-BTIbRjv/m5rcVTfBs4AMBLKs4x8XaaLkwm28KWu9S2vKNqXkXt2AH2Qf0sdPZHjFxcWg/YL53zcqAz+3g4/7PA==
```

Now today with me blowing away `yarn.lock` this is how it looks instead:

```
d3-selection@1.4.2, d3-selection@^1.1.0:
  version "1.4.2"
  resolved "https://registry.yarnpkg.com/d3-selection/-/d3-selection-1.4.2.tgz#dcaa49522c0dbf32d6c1858afc26b6094555bc5c"
  integrity sha512-SJ0BqYihzOjDnnlfyeHT0e30k0K1+5sR3d5fNueCNeuhZTnGw4M4o8mqJchSwgKMXCNFo+e2VTChiSJ0vYtXkg==
```

which works/worked.  At a guess, I'd say that in the former lockfile, where it was broken,`d3-transition` had a dep of `^1.1.0` which got resolved to `1.4.2` and at the time, `react-wordcloud` had a hard dependency on `1.4.1`.  Now that `react-wordcloud` had a hard dependency on `1.4.2`, they've been resolved to the same thing and been combined.  Generally different packages wouldn't be a problem, but perhaps not with how d3/wordcloud operates via Webpack -- I wonder if this is the core of the issue; I presume the problem will return if or when these two get out of sync.  It might well be a bug in yarn caused by a hard dependency or one changing, as you say an effect of a 'stale lockfile'...

So, where to from here.  As to whether `resolutions` is needed -- in my setup it's not being used so that looks safe to remove; yarn is resolving packages correctly and `"d3-selection": "1.4.1"` isn't a version being used.   As for the exact version dependency, assuming there's no issue with using the standard SemVer range version `^1.4.0` rather than a fixed version, then I think this would resolve the issue. If a specific minimum version is needed for a bug or security fix, then this could also be `^1.4.2` or above.  I've made a PR at #61 for both of these changes.  
 
Out of interest, I tried inspecting the lockfile before and after changes -- prior to the change running `yarn` produced 3 resolutions for 2 versions of `d3-selection` - hard dependencies on 1.4.1 and 1.4.2 and range of ^1.1.0. After making the changes in the PR, with that lockfile still present, yarn is still resolving `^1.1.0` to `1.4.1` -- so I wonder if the inconsistent `resolutions`, even though now removed, was actually causing the original problem.

Anyway, I believe that #61 will fix the problem going forward (at least until `d3-transition` changes major versions), just with the caveat that anyone seeing this issue should remove their lockfile and reinstall -- can't seem to fix it without that happening.

Phew.
